/* Copyright 2024 NXP
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#ifndef __EX_SSS_SET_CONFIG__
#define __EX_SSS_SET_CONFIG__

#define SET_CONFIG_WATCHDOG_TIMER_ENABLE 1

#define SET_CONFIG_WATCHDOG_TIMER_HWDTVALUE 0x00
#define SET_CONFIG_WATCHDOG_TIMER_AWDT1VALUE 0x00
#define SET_CONFIG_WATCHDOG_TIMER_AWDT2VALUE 0x00

#endif