/* Copyright 2025 NXP
 * SPDX-License-Identifier: BSD-3-Clause
 */

#ifndef __EX_SDM_VER_UID_RCTR_H__
#define __EX_SDM_VER_UID_RCTR_H__

#define EX_SSS_SDM_PICCDATA_OFFSET 0x20
#define EX_SSS_SDM_SDMENCOffset 0x60
#define EX_SSS_SDM_SDMENCLength 0x20
#define EX_SSS_SDM_SDMMACOffset 0x35
#define EX_SSS_SDM_SDMMACInputOffset 0x1B
#define EX_SSS_SDM_PICCDATA_LENGTH 0x20
#define EX_SSS_SDM_SDMSignatureLength 0x80
#define EX_SSS_SDM_7BYTE_VCUID_LENGTH 0x07
#define EX_SSS_SDM_SDMREADCTR_LENGTH 0x03
#define EX_SSS_SDM_ASCII_7BYTE_VCUID_LENGTH 0x0E
#define EX_SSS_SDM_ASCII_SDMREADCTR_LENGTH 0x06
#define EX_SSS_SDM_NDEF_FILE_NUMBER 0x02
#define EX_SSS_SDM_NDEF_FILE_SIZE 256
#define EX_SSS_SDM_SDMREADCTROffset 0x2C
#define EX_SSS_SDM_VCUIDOffset 0x1B

#endif // __EX_SDM_VER_UID_RCTR_H__