/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define PCR_IBE_ibe1 0x01u         /*!<@brief Input Buffer Enable: Enables */
#define PORT2_PCR4_MUX_mux00 0x00u /*!<@brief Pin Multiplex Control: Alternative 0 (GPIO) */

/*! @name PORT2_4 (number 18), AUTH_ARD_IO_EXP_INT
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_AUTH_ARD_IO_EXP_INT_GPIO GPIO2               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_AUTH_ARD_IO_EXP_INT_GPIO_PIN 4U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_AUTH_ARD_IO_EXP_INT_GPIO_PIN_MASK (1U << 4U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_AUTH_ARD_IO_EXP_INT_PORT PORT2               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_AUTH_ARD_IO_EXP_INT_PIN 4U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_AUTH_ARD_IO_EXP_INT_PIN_MASK (1U << 4U)      /*!<@brief PORT pin mask */
                                                                    /* @} */

/*! @name PORT3_12 (number 38), RGB_RED
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_RGB_RED_GPIO GPIO3                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_RGB_RED_INIT_GPIO_VALUE 0U        /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_RGB_RED_GPIO_PIN 12U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_RGB_RED_GPIO_PIN_MASK (1U << 12U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_RGB_RED_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_RGB_RED_PIN 12U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_RGB_RED_PIN_MASK (1U << 12U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PORT3_0 (number 46), RGB_BLUE
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_RGB_BLUE_GPIO GPIO3               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_RGB_BLUE_INIT_GPIO_VALUE 0U       /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_RGB_BLUE_GPIO_PIN 0U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_RGB_BLUE_GPIO_PIN_MASK (1U << 0U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_RGB_BLUE_PORT PORT3               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_RGB_BLUE_PIN 0U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_RGB_BLUE_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PORT3_13 (number 37), RGB_GREEN
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_RGB_GREEN_GPIO GPIO3                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_RGB_GREEN_GPIO_PIN 13U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_RGB_GREEN_GPIO_PIN_MASK (1U << 13U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_RGB_GREEN_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_RGB_GREEN_PIN 13U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_RGB_GREEN_PIN_MASK (1U << 13U)      /*!<@brief PORT pin mask */
                                                           /* @} */

/*! @name PORT3_15 (number 35), MCU_DBG_GPIO_D8
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_MCU_DBG_GPIO_D4_GPIO GPIO3                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_MCU_DBG_GPIO_D4_INIT_GPIO_VALUE 0U        /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_MCU_DBG_GPIO_D4_GPIO_PIN 15U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_MCU_DBG_GPIO_D4_GPIO_PIN_MASK (1U << 15U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_MCU_DBG_GPIO_D4_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_MCU_DBG_GPIO_D4_PIN 15U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_MCU_DBG_GPIO_D4_PIN_MASK (1U << 15U)      /*!<@brief PORT pin mask */
                                                                 /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
