/*
 * Copyright 2026 NXP
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */
#include <app_ndef.h>
#include <stdio.h>
#include <stdint.h>
#include <string.h>
#include <math.h>

#include "board.h"
#include "fsl_common_arm.h"
#include "peripherals.h"
#include "pin_mux.h"
#include "fsl_lpi2c.h"
#include "fsl_gpio.h"
#include "fsl_common_arm.h"
#include "clock_config.h"
#include "fsl_debug_console.h"

#include "nxLog_msg.h"
#include "platform.h"

#include "frdm_mcxa153_adc.h"
#include "app_auth_ard.h"
#include "app_nb_timer.h"

/*******************************************************************************
 * Definitions
 ******************************************************************************/
/** @brief Polling interval in milliseconds for the slider (potentiometer). */
#define SLIDER_READ_INTERVAL            50U

/** @brief Polling interval in milliseconds for the temperature sensor. */
#define TEMP_SENSOR_READ_INTERVAL       1000U

/** @brief Number of slider polling intervals per temperature sensor read cycle. */
#define TEMP_READ_INTERVAL_COUNT        (TEMP_SENSOR_READ_INTERVAL / SLIDER_READ_INTERVAL)

/*******************************************************************************
 * Prototypes
 ******************************************************************************/

/*******************************************************************************
 * Variables
 ******************************************************************************/
extern bool g_auth_ard_NdefRead_ISR_Flag;

/*!
 * @brief Main function
 *
 * This demo showcases:
 *  - Reading the AUTH-ARD slider (ADC) value (simulating an analog sensor)
 *  - Reading the AUTH-ARD temperature sensor value
 *  - Displaying both sensor values on the AUTH-ARD OLED display
 *  - NTAG X DNA trusted dynamic sensor readout via NFC phone (app-less)
 *	    The NDEF file contains a link to the NTAG Web Service along the sensor data.
 *      Each time the NFC-enabled phone reads the NDEF file, the NDEF file is updated
 *      via the NTAG X DNA I2C interface with the latest sensor data to ensure that
 *      the phone receives up-to-date information.
 *
 *      Next, an ECC signature over the full NDEF data is computed using the NTAG X DNA SDM
 *      (Secure Dynamic Messaging).
 *
 *      The NFC phone opens a NTAG Web Service link including sensor data and ECC signature
 *      in a browser. The service verifies the ECC signature generated by NTAG X DNA.
 *      It checks the tag UID, the SDM counter value (to prevent replay attacks), and the
 *      validity of the ECDSA Signature. After successful verification, the service displays
 *      authenticated sensor data on the phone.
 */
int main(void)
{
	sss_status_t sss_status = kStatus_SSS_Fail;
	int32_t app_ndef_status;

	uint16_t sliderValue     = 0;
    uint16_t old_sliderValue = 0;
    uint16_t sliderValueNdefFileOffset = 0;

    float tempSensorValue     = 0.0f;
    float old_tempSensorValue = 0.0f;
    uint16_t tempSensorValueNdefFileOffset = 0;

    /* Counter to trigger temperature reads less frequently than slider reads */
    uint32_t tempSensorReadCounter = TEMP_READ_INTERVAL_COUNT + 1U;

    uint8_t updateDisplay = 0;
    app_nb_timer_t app_nb_timer = {0}; /* Non-blocking application timer */


    /* -------------------------------- */
    /*      Hardware Initialization     */
    /* -------------------------------- */
    platform_boot_direct(); /* FRDM MCXA153 board and NX middleware */
    DisableIRQ(AUTH_ARD_IO_EXP_IRQ); /* Disable AUTH-ARD I/O port expander interrupt */

    app_auth_ard_i2c_Interface_Init(LPI2C_BAUDRATE); /* AUTH-ARD I2C bus */
    app_auth_ard_io_expander_Init(); /* AUTH-ARD I/O port expander */

    adc_Init(); /* FRDM MCXA153 ADC (AUTH-ARD slider) */

    /* -------------------------------- */
    /*      AUTH-ARD OLED               */
    /* -------------------------------- */
    auth_ard_OLED_Init();

    /* -------------------------------- */
    /*      NTAG X DNA                  */
    /* -------------------------------- */

    /* Read the NDEF file via I2C and obtain the sensor value field offsets.
    * Since the NTAG X DNA device does not support concurrent I2C and NFC communication,
    * a cold reset is triggered via the NFC interface to release the active interface assignment.
    */
     app_ndef_status = app_getSensorValueNdefFileOffset(NDEF_FILE_SENSOR_VALUE_TOCKEN, &sliderValueNdefFileOffset,
    							 	 	 	 	   NDEF_FILE_TEMP_VALUE_TOKEN,&tempSensorValueNdefFileOffset);
    
    /* Check if NDEF file offset retrieval was successful */
    if( APP_NDEF_OK != app_ndef_status)
    {
        /* Display error message on OLED */
        auth_ard_OLED_ClearBuffer();
        auth_ard_OLED_SetFont(u8g2_font_profont15_mf);
        auth_ard_OLED_Print(5, 12, "ERROR:");
        
        /* Display specific error message based on error code */
    	if(APP_NDEF_NDEF_FILE_READ_FAILED == app_ndef_status)
    	{
            auth_ard_OLED_Print(5, 28, "NDEF READ FAILED");
    	}
    	else if(APP_NDEF_FILE_EMPTY == app_ndef_status)
    	{
    		auth_ard_OLED_Print(5, 28, "EMPTY NDEF FILE");
    	}
    	else if(APP_NDEF_TOKEN_PARSE_FAILED == app_ndef_status)
    	{
    		auth_ard_OLED_Print(5, 28, "WRONG NDEF FORMAT");
    	}
    	else
    	{
             /* Unknown error */
    		auth_ard_OLED_Print(5, 28, "NDEF FILE ");
    	}
    	auth_ard_OLED_UpdateDisplay();

        /* Halt execution and wait for MCU reset */
    	while(true); 
    }

    /* Clear NTAG X DNA GPIO2 ISR flags */
    g_auth_ard_NdefRead_ISR_Flag = false;

    /* Trigger the first sensor read and display update  */
    app_nb_timer_start(&app_nb_timer, 0U);

    /* -------------------------------- */
    /*            Main Loop             */
    /* -------------------------------- */
    for (;;)
    {
        /* ---- Periodic sensor read and display update ---- */
        if (app_nb_timer_expired(&app_nb_timer))
        {
            /* Disable interrupt during I2C sensor reads to avoid I2C-bus conflicts */
            DisableIRQ(AUTH_ARD_IO_EXP_IRQ);

            /* Restart the timer for the next slider read interval */
            app_nb_timer_start(&app_nb_timer, SLIDER_READ_INTERVAL);

            /* Read slider (potentiometer) value via ADC */
            sliderValue = auth_ard_Slider_ReadValue();
            if (sliderValue != old_sliderValue)
            {
                updateDisplay = true;
            }

            /* Read temperature sensor at a slower rate than the slider */
            if (tempSensorReadCounter > TEMP_READ_INTERVAL_COUNT)
            {
                tempSensorReadCounter = 0;

                auth_ard_TempSensor_ReadValue(&tempSensorValue);

                if (tempSensorValue != old_tempSensorValue)
                {
                    updateDisplay = true;
                }
            }
            tempSensorReadCounter++;

            /* Update OLED display only if a value changed and no NFC NDEF file read is in progress */
            if (updateDisplay == true && g_auth_ard_NdefRead_ISR_Flag == false)
            {
                updateDisplay = false;

                auth_ard_OLED_ClearBuffer();

                /* Display temperature value */
                auth_ard_OLED_SetFont(u8g2_font_profont22_mf);
                auth_ard_OLED_Printf(12, 20, "%2.1f", tempSensorValue);

                /* Display slider value */
                auth_ard_OLED_Printf(80, 20, "%3d", sliderValue);

                /* Display degree Celsius symbol next to temperature */
                auth_ard_OLED_SetFont(u8g2_font_profont15_mf);
                auth_ard_OLED_Print(60, 17, "\260C");

                /* Display slider value as a bar graph at the bottom of the screen */
                auth_ard_OLED_BarGraph(sliderValue);

                auth_ard_OLED_UpdateDisplay();
            }

            /* Save current values for change detection on next iteration */
            old_tempSensorValue = tempSensorValue;
            old_sliderValue     = sliderValue;

            /* Re-enable interrupt after I2C sensor reads are complete */
            EnableIRQ(AUTH_ARD_IO_EXP_IRQ);
        }

        /* ---- NFC NDEF file read Event Handling ---- */
        if (g_auth_ard_NdefRead_ISR_Flag == true)
        {
            g_auth_ard_NdefRead_ISR_Flag = false;

            /* An NFC-enabled phone has initiated an NDEF file read.
             *
             * Reading the NDEF file causes the NTAG X DNA to toggle GPIO2.
             * On the AUTH-ARD Shield, NTAG X DNA GPIO2 is connected to the
             * BIO2 input of the I2C port expander. The port expander asserts
             * its INT output, which is connected to the MCU Arduino header
             * pin D3. The associated interrupt handler sets
             * g_auth_ard_NdefRead_ISR_Flag to true, allowing the main
             * application loop to process the NDEF read event outside the
             * interrupt context.
             *
             * The NTAG X DNA NFCPause feature temporarily extends the NFC
             * frame waiting time by sending ISO/IEC 14443-4 S(WTX) requests.
             * This gives the host MCU additional time to update dynamic NDEF
             * file contents via the I2C interface before the NFC reader
             * receives the requested data.
             *
             * While NFCPause is active, update the dynamic NDEF fields with
             * the latest sensor values so that the NFC reader receives
             * up-to-date information when the transaction resumes.
             *
             * After the sensor update, the MCU sends a ManageGPIO command
             * via I2C to toggle NTAG X DNA GPIO2. This releases the
             * NFCPause feature, stops the transmission of S(WTX) requests,
             * and allows the NTAG X DNA to return the updated NDEF file
             * contents via the NFC interface.
             */
            sss_status = app_updateNdefFile(sliderValue, sliderValueNdefFileOffset,
                           	   	   	    tempSensorValue, tempSensorValueNdefFileOffset);

            if( kStatus_SSS_Success == sss_status )
            {
            	LOG_I("Update NDEF file Success !!!...");
            }
            else
            {
            	/* NDEF file update failed (e.g. user removed
            	 * the NFC-enabled phone - reset the auth device */
            	LOG_E("Update NDEF file Failed !!!...");
            }

        }
    } /* for(;;) */
}
