# Copyright 2023-2024 NXP
#
# SPDX-License-Identifier: BSD-3-Clause
#
# #############################################################
# This file is generated using a script
# #############################################################
#
IF(SSS_HAVE_NX_TYPE_NX_R_DA OR SSS_HAVE_NX_TYPE_NX_PICC)
    SET(SSS_HAVE_NX_TYPE ON)
ELSE()
    SET(SSS_HAVE_NX_TYPE OFF)
ENDIF()
IF(SSS_HAVE_MBEDTLS_ALT_SSS)
    SET(SSS_HAVE_MBEDTLS_ALT ON)
ELSE()
    SET(SSS_HAVE_MBEDTLS_ALT OFF)
ENDIF()
IF(SSS_HAVE_HOSTCRYPTO_MBEDTLS OR SSS_HAVE_HOSTCRYPTO_OPENSSL OR SSS_HAVE_HOSTCRYPTO_USER)
    SET(SSS_HAVE_HOSTCRYPTO_ANY ON)
ELSE()
    SET(SSS_HAVE_HOSTCRYPTO_ANY OFF)
ENDIF()
IF(SSS_HAVE_HOST_LPCXPRESSO55S OR SSS_HAVE_HOST_FRDMMCXA153 OR SSS_HAVE_HOST_FRDMMCXN947)
    SET(SSS_HAVE_HOST_EMBEDDED ON)
ELSE()
    SET(SSS_HAVE_HOST_EMBEDDED OFF)
ENDIF()

IF(SSS_HAVE_HOST_FRDMK64F AND SSS_HAVE_NX_TYPE)
    IF(NOT (SSS_HAVE_SMCOM_SCI2C OR SSS_HAVE_SMCOM_T1OI2C_GP1_0 OR SSS_HAVE_SMCOM_PN7150))
        MESSAGE(
            FATAL_ERROR
                "One of 'SSS_HAVE_SMCOM_SCI2C, SSS_HAVE_SMCOM_T1OI2C_GP1_0, SSS_HAVE_SMCOM_PN7150' must be set[for SSS_HAVE_HOST_FRDMK64F AND SSS_HAVE_NX_TYPE]."
        )
    ENDIF()
ENDIF(SSS_HAVE_HOST_FRDMK64F AND SSS_HAVE_NX_TYPE)

IF(SSS_HAVE_HOST_EVKMIMXRT1060 AND SSS_HAVE_NX_TYPE)
    IF(NOT (SSS_HAVE_SMCOM_SCI2C OR SSS_HAVE_SMCOM_T1OI2C_GP1_0))
        MESSAGE(
            FATAL_ERROR
                "One of 'SSS_HAVE_SMCOM_SCI2C, SSS_HAVE_SMCOM_T1OI2C_GP1_0' must be set[for SSS_HAVE_HOST_EVKMIMXRT1060 AND SSS_HAVE_NX_TYPE]."
        )
    ENDIF()
ENDIF(SSS_HAVE_HOST_EVKMIMXRT1060 AND SSS_HAVE_NX_TYPE)


IF(SSS_HAVE_HOST_LPCXPRESSO55S AND SSS_HAVE_MBEDTLS_3_X AND SSS_HAVE_RTOS_FREERTOS)
    MESSAGE(FATAL_ERROR
                    "Only MbedTLS 2.X is supported for LPC55S + FreeRTOS"
            )
ENDIF()

IF(SSS_HAVE_HOST_FRDMMCXA153 AND SSS_HAVE_RTOS_FREERTOS)
    MESSAGE(FATAL_ERROR
                    "FreeRTOS is not supported for MCXA153 Platform"
            )
ENDIF()

IF(SSS_HAVE_HOST_FRDMMCXA153 AND SSS_HAVE_ALL_AUTH_CODE_ENABLED)
    MESSAGE(FATAL_ERROR
                    "Due to memory constraints, ALL_AUTH_CODE must be disabled for MCXA153 platform"
            )
ENDIF()

IF(SSS_HAVE_HOST_FRDMMCXA153 AND (SSS_HAVE_MBEDTLS_ALT_SSS OR SSS_HAVE_MBEDTLS_ALT_PSA))
    MESSAGE(FATAL_ERROR
                    "Due to memory constraints, ALL_AUTH_CODE must be disabled for MCXA153 platform"
            )
ENDIF()

IF(SSS_HAVE_HOST_PCLINUX64 AND SSS_HAVE_SMCOM_T1OI2C_GP1_0)
    MESSAGE(FATAL_ERROR
                    "T1OI2C_GP1_0 SMCOM option not supported on PCLINUX"
            )
ENDIF()


IF((SSS_HAVE_MBEDTLS_3_X OR SSS_HAVE_MBEDTLS_2_X) AND WithSharedLIB)
    MESSAGE(FATAL_ERROR
                    "Shared Library is not supported for MbedTLS Host Crypto. Please disable shared library option"
            )
ENDIF()

IF (SSS_HAVE_AUTH_SYMM_DIVERSIFY_ENABLED AND (NOT SSS_HAVE_AUTH_SYMM_AUTH))
    MESSAGE(FATAL_ERROR
                    "Diversify enabled only with Symmetric Authentication"
            )
ENDIF()