# Copyright 2023-2024 NXP
#
# SPDX-License-Identifier: BSD-3-Clause
#
# #############################################################
# This file is generated using a script
# #############################################################
#
IF(SSS_HAVE_NX_TYPE_NX_R_DA OR SSS_HAVE_NX_TYPE_NX_PICC)
    SET(SSS_HAVE_NX_TYPE ON)
ELSE()
    SET(SSS_HAVE_NX_TYPE OFF)
ENDIF()
IF(SSS_HAVE_MBEDTLS_ALT_SSS)
    SET(SSS_HAVE_MBEDTLS_ALT ON)
ELSE()
    SET(SSS_HAVE_MBEDTLS_ALT OFF)
ENDIF()
IF(SSS_HAVE_HOSTCRYPTO_MBEDTLS OR SSS_HAVE_HOSTCRYPTO_OPENSSL OR SSS_HAVE_HOSTCRYPTO_USER)
    SET(SSS_HAVE_HOSTCRYPTO_ANY ON)
ELSE()
    SET(SSS_HAVE_HOSTCRYPTO_ANY OFF)
ENDIF()

IF(SSS_HAVE_HOST_FRDMK64F AND SSS_HAVE_NX_TYPE)
    IF(NOT (SSS_HAVE_SMCOM_SCI2C OR SSS_HAVE_SMCOM_T1OI2C_GP1_0 OR SSS_HAVE_SMCOM_PN7150))
        MESSAGE(
            FATAL_ERROR
                "One of 'SSS_HAVE_SMCOM_SCI2C, SSS_HAVE_SMCOM_T1OI2C_GP1_0, SSS_HAVE_SMCOM_PN7150' must be set[for SSS_HAVE_HOST_FRDMK64F AND SSS_HAVE_NX_TYPE]."
        )
    ENDIF()
ENDIF(SSS_HAVE_HOST_FRDMK64F AND SSS_HAVE_NX_TYPE)

IF(SSS_HAVE_HOST_EVKMIMXRT1060 AND SSS_HAVE_NX_TYPE)
    IF(NOT (SSS_HAVE_SMCOM_SCI2C OR SSS_HAVE_SMCOM_T1OI2C_GP1_0))
        MESSAGE(
            FATAL_ERROR
                "One of 'SSS_HAVE_SMCOM_SCI2C, SSS_HAVE_SMCOM_T1OI2C_GP1_0' must be set[for SSS_HAVE_HOST_EVKMIMXRT1060 AND SSS_HAVE_NX_TYPE]."
        )
    ENDIF()
ENDIF(SSS_HAVE_HOST_EVKMIMXRT1060 AND SSS_HAVE_NX_TYPE)
