/*
 *
 * Copyright 2022-2024 NXP
 * SPDX-License-Identifier: BSD-3-Clause
 */

#ifndef NX_CONST_H
#define NX_CONST_H

#if defined(SSS_USE_FTR_FILE)
#include "fsl_sss_ftr.h"
#else
#include "fsl_sss_ftr_default.h"
#endif

#define CALC_NX_CONF_GPIO_PAD_CTRL(A, B, C, D) ((A << (8 * 3)) | (B << (8 * 2)) | (C << (8 * 1)) | D)

#define NX_MAX_BUF_SIZE_CMD (1024)
#define NX_MAX_BUF_SIZE_RSP (1024)
#define NX_MAX_STANDARD_DATA_FILE_SIZE (1024)
#define NX_MAX_CERTIFICATE_SIZE (650)
#define NX_I2CM_MAX_BUF_SIZE_CMD (271)
#define NX_MAX_SHA_INPUT_LEN (220)
#define NX_FILE_ID_LIST_SIZE (32)
#define NX_NUM_CARD_CONFIGURATIONS 24
#define NX_POLICY_BUF_SIZE 3
#define NX_TB_POLICY_MAX_COUNT 8
#define NX_SB_POLICY_MAX_COUNT 14
#define NX_KEY_SETTING_CRYPTO_KEY_META_DATA_BYTES 4 /** Number of metadata bytes in crypto request key type */
#define NX_KEY_SETTING_CRYPTO_KEY_MAX_ENTRY 8
#define NX_KEY_SETTING_CRYPTO_KEY_NO_OFFSET 0
#define NX_KEY_SETTING_CRYPTO_KEY_TYPE_OFFSET 1
#define NX_KEY_SETTING_CRYPTO_KEY_POLICY_OFFSET 2
#define NX_KEY_SETTING_ECC_KEY_MAX_ENTRY 5
#define NX_KEY_SETTING_ECC_KEY_META_DATA_BYTES 13
#define NX_KEY_SETTING_ECC_KEY_NO_OFFSET 0
#define NX_KEY_SETTING_ECC_KEY_CURVE_ID_OFFSET 1
#define NX_KEY_SETTING_ECC_KEY_POLICY_OFFSET 2
#define NX_KEY_SETTING_ECC_KEY_WRITE_ACCESS_OFFSET 4
#define NX_KEY_SETTING_ECC_KEY_USAGE_CTR_LIMIT_OFFSET 5
#define NX_KEY_SETTING_ECC_KEY_USAGE_CTR_OFFSET 9
#define NX_KEY_SETTING_CAROOTKEY_MAX_ENTRY 5
#define NX_KEY_SETTING_CAROOTKEY_META_DATA_BYTES 7
#define NX_KEY_SETTING_CAROOTKEY_NO_OFFSET 0
#define NX_KEY_SETTING_CAROOTKEY_CURVE_ID_OFFSET 1
#define NX_KEY_SETTING_CAROOTKEY_ACCESS_BITMAP_OFFSET 2
#define NX_KEY_SETTING_CAROOTKEY_WRITE_ACCESS_OFFSET 4

#define NX_CONF_SLOT_USAGE_POLICY_INPUT_ENABLED (1 << 0)
#define NX_CONF_SLOT_USAGE_POLICY_KEY_ENABLED (1 << 1)
#define NX_CONF_SLOT_ALGO_HMAC_ENABLED (1 << 0)
#define NX_CONF_SLOT_ALGO_HKDF_ENABLED (1 << 1)
#define NX_CONF_SLOT_ALGO_SHA_ENABLED (1 << 2)
#define NX_CONF_SLOT_ALGO_AES_ENABLED (1 << 3)
#define NX_CONF_SLOT_ALGO_ECDSA_ENABLED (1 << 4)

#define NX_GPIO_OUTPUT_PAUSE_NFC (1 << 7)
#define NX_GPIO_OUTPUT_RELEASE_PAUSE_NFC (1 << 7)
#define NX_GPIO_OUTPUT_NO_NFC_ACTION (0 << 7)
#define NX_GPIO_POWEROUT_ENABLE (1 << 0)

#define NX_CRYPTOAES_KEYID 0x80
#define NX_CRYPTOAES_SLOTNUM 0x00

#define NX_CONF_FEATURE_UNILATERAL_AUTH_ENABLED (1 << 13)
#define NX_CONF_FEATURE_IMPORT_KEY_ENABLED (1 << 12)
#define NX_CONF_FEATURE_DATA_1K_LIMIT_ENABLED (1 << 11)
#define NX_CONF_FEATURE_COUNTER_ENABLED (1 << 10)
#define NX_CONF_FEATURE_ECDSA_V4_ENABLED (1 << 8)
#define NX_CONF_FEATURE_CCM_ENABLED (1 << 7)
#define NX_CONF_FEATURE_EV2_AES256_ENABLED (1 << 6)
#define NX_CONF_FEATURE_EV2_AES128_ENABLED (1 << 5)
#define NX_CONF_FEATURE_CRYPTO_ECC_ENABLED (1 << 4)
#define NX_CONF_FEATURE_CRYPTO_AES_ENABLED (1 << 3)
#define NX_CONF_FEATURE_GPIO_ENABLED (1 << 2)
#define NX_CONF_FEATURE_I2C_ENABLED (1 << 1)
#define NX_CONF_FEATURE_NFC_ENABLED (1 << 0)
#define NX_CONF_PICC_USERID (1 << 1)
#define NX_CONF_SMCONFIG_NO_CHANGE (0 << 2)
#define NX_CONF_SMCONFIG_DISABLE_CHAIN_WRITE (1 << 2)
#define NX_CONF_SILENTMODE_CUSTOMIZED_REQS_WUPS_ENABLE \
    (1 << 1) /* Silent Mode Configuration: Customized REQS/WUPS enabling*/
#define NX_CONF_SILENTMODE_SILENT_ENABLE (1 << 0)
#define NX_CONF_PRIVACY_ORIGINALITY_DISABLED (1 << 2)
#define NX_CONF_PRIVACY_MANU_MASK_ENABLED (1 << 1)
#define NX_CONF_PRIVACY_APPPRIVACYKEY_ENABLED (1 << 0)
#define NX_CONF_NFC_ENABLED (1 << 0)
#define NX_CONF_NFC_DISABLED (0 << 0)
#define NX_CONF_I2C_ENABLED (1 << 0)
#define NX_CONF_I2C_DISABLED (0 << 0)
#define NX_CONF_PROTOCOL_OPTIONS_SIGI_VERIFIER_ENABLED (1 << 12)
#define NX_CONF_PROTOCOL_OPTIONS_SIGI_PROVER_ENABLED (1 << 11)
#define NX_CONF_PROTOCOL_OPTIONS_CARD_UNILATERAL_ENABLED (1 << 2)
#define NX_CONF_PROTOCOL_OPTIONS_SYMM_AUTH_ENABLED (1 << 0)
#define NX_CONF_PROTOCOL_OPTIONS_SECURE_TUNNEL_NTAGEV2_SUPPORTED (1 << 10)
#define NX_CONF_PROTOCOL_OPTIONS_SECURE_TUNNEL_AES256_SUPPORTED (1 << 9)
#define NX_CONF_PROTOCOL_OPTIONS_SECURE_TUNNEL_AES128_SUPPORTED (1 << 8)
#define NX_CONF_PROTOCOL_OPTIONS_CONTROLLER_SESSION_KEY_ENABLED (1 << 7)
#define NX_CONF_GPIO_INIT_STATE (1 << 0)
#define NX_CONF_GPIO_I2C_SUPPORT_ENABLED (1 << 1)
#define NX_CONF_GPIO_BACKPOWER_ENABLED (1 << 0)
#define NX_CONF_GPIO_DEBOUNCE_FILTER_ENABLED (0x00000400)
#define NX_CONF_GPIO_INPUT_FILTER_SELECTION_MASK (0x00000300)
#define NX_CONF_GPIO_INPUT_CONF_MASK (0x000000E0)
#define NX_CONF_GPIO_OUTPUT_CONF_MASK (0x0000001E)
#define NX_CONF_GPIO_SUPPLY_SELECTION_MASK (1)
#define NX_CONF_GPIO_DEBOUNCE_FILTER_VALUE_MASK (0x03FF0000)
#define NX_CONF_GPIO_DEBOUNCE_FILTER_VALUE_PADCTRL_A_MASK (0x0300)
#define NX_CONF_GPIO_DEBOUNCE_FILTER_VALUE_PADCTRL_B_MASK (0x00FF)
#define NX_CONF_GPIO_HIGH_SPEED (1 << 0)
#define NX_CONF_CRYPTOAPI_ASYMMETRIC_ENABLED (1 << 1)
#define NX_CONF_CRYPTOAPI_ASYMMETRIC_DISABLED (0 << 1)
#define NX_CONF_CRYPTOAPI_SYMMETRIC_ENABLED (1 << 0)
#define NX_CONF_CRYPTOAPI_SYMMETRIC_DISABLED (0 << 0)
#define NX_CONF_HALT_WAKEUPA_GPIO_WAKEUP_ENABLED (1 << 6)
#define NX_CONF_HALT_WAKEUPB_I2C_WAKEUP_ENABLED (1 << 2)
#define NX_CONF_HALT_WAKEUPB_I2C_SDA_WAKEUP_ENABLED (1 << 1)
#define NX_CONF_HALT_WAKEUPB_NFC_FIELD_WAKEUP_ENABLED (1 << 0)
#define NX_CONF_HALT_OPTION_GPIO2_RESET_ENABLED (1 << 1)
#define NX_CONF_HALT_OPTION_GPIO1_RESET_ENABLED (1 << 0)
#define NX_MGMT_KEYPAIR_POLICY_FREEZE_KUCLIMIT (1 << 15)
#define NX_MGMT_KEYPAIR_POLICY_CARD_UNILATERAL (1 << 8)
#define NX_MGMT_KEYPAIR_POLICY_SDM_ENABLED (1 << 5)
#define NX_MGMT_KEYPAIR_POLICY_ECC_SIGN_ENABLED (1 << 4)
#define NX_MGMT_KEYPAIR_POLICY_ECDH_ENABLED (1 << 3)
#define NX_MGMT_KEYPAIR_POLICY_SIGMAI_ENABLED (1 << 2)
#define NX_MGMT_KEYPAIR_POLICY_ECDSA_V4_ENABLED (1 << 1)
#define NX_MGMT_KEYPAIR_POLICY_HKDF_ENABLED (1 << 8)
#define NX_MGMT_KEYPAIR_POLICY_HMAC_ENABLED (1 << 7)
#define NX_MGMT_KEYPAIR_POLICY_AEAD_ENC_INTERANL_NONCE_ENABLED (1 << 6)
#define NX_MGMT_KEYPAIR_POLICY_AEAD_ENC_ENABLED (1 << 5)
#define NX_MGMT_KEYPAIR_POLICY_AEAD_DEC_ENABLED (1 << 4)
#define NX_MGMT_KEYPAIR_POLICY_ECB_CBC_ENC_ENABLED (1 << 3)
#define NX_MGMT_KEYPAIR_POLICY_ECB_CBC_DEC_ENABLED (1 << 2)
#define NX_MGMT_KEYPAIR_POLICY_MAC_SIGN_ENABLED (1 << 1)
#define NX_MGMT_KEYPAIR_POLICY_MAC_VERIFY_ENABLED (1 << 0)
#define NX_MGMT_NFC_ACTION_NO_NFC (0 << 7)
#define NX_MGMT_NFC_ACTION_PAUSE_NFC (1 << 7)
#define NX_MGMT_NFC_ACTION_RELEASE_NFC_PAUSE (1 << 7)
#define NX_MGMT_NFC_ACTION_OFFSET 7
#define NX_MGMT_NFC_ACTION_MASK 0x80
#define NX_MGMT_NFC_ACTION_BITSHIFT 7
#define NX_MGMT_GPIO_MODE_DOWN_STREAM_POWER_OUT_OFFSET 2
#define NX_MGMT_GPIO_MODE_DOWN_STREAM_POWER_OUT_BITSHIFT 2
#define NX_MGMT_GPIO_MEASUREMENT_CONTROL_NO_MEASURE (0 << 1)
#define NX_MGMT_GPIO_MEASUREMENT_CONTROL_EXECUTE_MEASURE (1 << 1)
#define NX_MGMT_GPIO_MEASUREMENT_CONTROL_EXTRACT 0x02
#define NX_MGMT_GPIO_MEASUREMENT_CONTROL_OFFSET 1
#define NX_MGMT_GPIO_MEASUREMENT_STOP_POWER_HARVESTING (0 << 0)
#define NX_MGMT_GPIO_MEASUREMENT_ENABLE_POWER_HARVESTING (1 << 0)
#define NX_MGMT_GPIO_CONTROL_EXTRACT 0x03
#define NX_MGMT_NFC_ACTION_NFC_RELEASE_PAUSE 0x80

#define NX_MAX_NFC_PAUSE_DATA_LEN 239

#define NX_CONF_AUTH_COUNTER_AES_AUTH_ENABLED (1 << 0)
#define NX_CONF_AUTH_COUNTER_AES_AUTH_ENABLED_OFFSET (0)
#define NX_CONF_AUTH_COUNTER_AES_AUTH_ENABLED_MASK (0x01)
#define NX_CONF_COMM_MODE_OFFSET (4)
#define NX_CONF_AC_OFFSET (0)

#define NX_CONF_COMM_MODE_MASK (0x30)
#define NX_CONF_AC_MASK (0x0F)
#define NX_CONF_COMM_MODE_AND_AC_MASK (0x3F)

#define NX_CONF_PICC_USERID_MASK (0x02)
#define NX_CONF_SMCONFIG_DISABLE_CHAIN_WRITE_OFFSET (2)
#define NX_CONF_SMCONFIG_BYTE_A_RFU_MASK (0x00)
#define NX_CONF_SMCONFIG_BYTE_B_MASK (0x04)
#define NX_CONF_CAPABILITY_DATA_PDCAP2_5_INDEX (8)
#define NX_CONF_CAPABILITY_DATA_PDCAP2_6_INDEX (9)
#define NX_CONF_CAPABILITY_DATA_LEN (10)
#define NX_CONF_CAPABILITY_RFU_DATA_LEN (8)
#define NX_CONF_SILENTMODE_CUSTOMIZED_REQS_WUPS_OFFSET (1)
#define NX_CONF_SILENTMODE_SILENT_OPTIONS_MASK (0x03)
#define NX_CONF_SILENTMODE_SILENT_OFFSET (0)
#define NX_CONF_PRIVACY_FEATURES_MASK (0x07)
#define NX_CONF_PRIVACY_ORIGINALITY_DISABLED_OFFSET (2)
#define NX_CONF_PRIVACY_MANU_MASK_ENABLED_OFFSET (1)
#define NX_CONF_PRIVACY_APPPRIVACYKEY_ENABLED_OFFSET (0)
#define NX_CONF_NFC_SUPPORT_MASK (0x01)
#define NX_CONF_NFC_ENABLED_OFFSET (0)
#define NX_CONF_I2C_SUPPORT_MASK (0x01)
#define NX_CONF_I2C_ENABLED_OFFSET (0)
#define NX_CONF_GPIO_INIT_STATE_OFFSET (0)
#define NX_CONF_GPIO_I2C_SUPPORT_ENABLED_OFFSET (1)
#define NX_CONF_GPIO_BACKPOWER_ENABLED_OFFSET (0)
#define NX_CONF_GPIO_DEBOUNCE_FILTER_ENABLED_OFFSET (2)
#define NX_CONF_GPIO_INPUT_FILTER_SELECTION_OFFSET (0)
#define NX_CONF_GPIO_INPUT_CONF_OFFSET (5)
#define NX_CONF_GPIO_OUTPUT_CONF_OFFSET (1)
#define NX_CONF_GPIO_SUPPLY_SELECTION_OFFSET (0)
#define NX_CONF_CERT_FEATURE_SELECTION_MASK (0x1F)
#define NX_CONF_CERT_LEAF_CACHE_SIZE_MIN (1)
#define NX_CONF_CERT_LEAF_CACHE_SIZE_MAX (8)
#define NX_CONF_CERT_INTERM_CACHE_SIZE_MIN (2)
#define NX_CONF_CERT_INTERM_CACHE_SIZE_MAX (8)
#define NX_CONF_CERT_HOSTCERT_SUPPORT (0x01)
#define NX_CONF_CERT_HOSTCERT_SUPPORT_OFFSET (3)
#define NX_CONF_CERT_INTERNALCERT_SUPPORT (0x00)
#define NX_CONF_CERT_INTERNALCERT_SUPPORT_OFFSET (1)
#define NX_CONF_CERT_SIGMA_I_CACHE_ENABLED (1 << 0)
#define NX_CONF_CERT_SIGMA_I_CACHE_DISABLED (0 << 0)
#define NX_CONF_CRYPTOAPI_SUPPORT_MASK (0x03)
#define NX_CONF_CRYPTOAPI_ASYMMETRIC_SUPPORT_OFFSET (1)
#define NX_CONF_CRYPTOAPI_SYMMETRIC_SUPPORT_OFFSET (0)
#define NX_CONF_HALT_WAKEUPA_GPIO_WAKEUP_ENABLED_OFFSET (6)
#define NX_CONF_HALT_WAKEUPA_I2C_WAKEUP_ADDRESS_MAX (0x7F)
#define NX_CONF_HALT_WAKEUP_I2C_WAKEUP_ADDRESS_MAX (0x7F)
#define NX_CONF_HALT_WAKEUP_I2C_WAKEUP_ADDRESS_MASK (0x7F)
#define NX_CONF_HALT_WAKEUPA_I2C_WAKEUP_ADDRESS_MASK (0x3F)
#define NX_CONF_HALT_WAKEUPA_I2C_WAKEUP_ADDRESS_BIT_SHIFT (0x01)
#define NX_CONF_HALT_WAKEUPB_I2C_WAKEUP_ADDRESS_MASK (0x80)
#define NX_CONF_HALT_WAKEUPB_I2C_WAKEUP_ADDRESS_BITOFFSET (7)
#define NX_CONF_HALT_WAKEUPA_I2C_WAKEUP_CYCLE_MAX (0xF)
#define NX_CONF_HALT_WAKEUPB_I2C_WAKEUP_CYCLE_MASK (0x78)
#define NX_CONF_HALT_WAKEUPB_I2C_SDA_WAKEUP_CYCLE_MASK (0x0F)
#define NX_CONF_HALT_WAKEUPB_I2C_WAKEUP_CYCLE_BITOFFSET (3)
#define NX_CONF_HALT_WAKEUPB_I2C_WAKEUP_ENABLED_OFFSET (2)
#define NX_CONF_HALT_WAKEUPB_I2C_SDA_WAKEUP_ENABLED_OFFSET (1)
#define NX_CONF_HALT_WAKEUPB_NFC_FIELD_WAKEUP_ENABLED_OFFSET (0)
#define NX_CONF_HALT_OPTION_GPIO_RESET_MASK (0x03)
#define NX_CONF_HALT_OPTION_GPIO2_RESET_ENABLED_OFFSET (1)
#define NX_CONF_HALT_OPTION_GPIO1_RESET_ENABLED_OFFSET (0)

#define NX_CONF_DEFER_SDM_ENC_ENABLED (1 << 0)
#define NX_CONF_DEFERRAL_COUNT_MAX 0x3
#define NX_CONF_DEFERRAL_SIZE 2
#define NX_CONF_DEFERRAL_METHOD_NO_DEFERRAL 0x00
#define NX_CONF_DEFERRAL_METHOD_NUM_BOOT_1 0x01
#define NX_CONF_DEFERRAL_METHOD_NUM_BOOT_2 0x02
#define NX_CONF_DEFERRAL_METHOD_NUM_BOOT_3 0x03
#define NX_CONF_DEFERRAL_METHOD_NUM_BOOT_4 0x04
#define NX_CONF_DEFERRAL_METHOD_NUM_BOOT_5 0x05
#define NX_CONF_DEFERRAL_METHOD_NUM_BOOT_6 0x06
#define NX_CONF_DEFERRAL_METHOD_NUM_BOOT_7 0x07
#define NX_CONF_DEFERRAL_METHOD_ACTIVATE_CONFIG 0xFF

#define NX_CONF_UID_FORMAT_LENGTH 0x00
#define NX_CONF_UID_LENGTH_7_BYTES 0x07
#define NX_CONF_UID_LENGTH_10_BYTES 0x0A

#define NX_ACTIVATE_CONF_COUNT_MAX 0x4
#define NX_ACTIVATE_CONF_ELEMENT_SIZE 2

#define NX_CRYPTOREQ_AEAD_VERIFYRESULT_SIZE 2
#define NX_CRYPTOREQ_AEAD_AES_GCM_MAX_NONCE_LEN 60
#define NX_CRYPTOREQ_AEAD_AES_GCM_MIM_NONCE_LEN 12
#define NX_CRYPTOREQ_AEAD_AES_CCM_NONCE_LEN 13
#define NX_CRYPTOREQ_AEAD_AES_MAX_TAG_LEN 16
#define NX_CRYPTOREQ_AEAD_AES_CCM_MAX_TAG_LEN 16
#define NX_CRYPTOREQ_AEAD_AES_CCM_MIN_TAG_LEN 8
#define NX_CRYPTOREQ_AEAD_AES_GCM_MAX_TAG_LEN 16
#define NX_CRYPTOREQ_AEAD_AES_GCM_MIN_TAG_LEN 12

#define NX_CRYPTOREQ_ECHO_MAX_FULL_ADD_DATA_LEN 238
#define NX_CRYPTOREQ_ECHO_MAX_MAC_ADD_DATA_LEN 246
#define NX_CRYPTOREQ_ECHO_MAX_PLAIN_ADD_DATA_LEN 254

#define NX_FILE_NO_MASK (0x1F)
#define NX_FILE_SIZE_MIN (0x1)
#define NX_FILE_SIZE_MAX (0xFFFFFF)

#define NX_FILE_SETTINGS_OPTION_SDM (1 << 6)
#define NX_FILE_SETTINGS_OPTION_COMMMODE_MASK (0x03)

#define NX_FILE_AR_READ_MASK (0x0F)
#define NX_FILE_AR_READ_OFFSET (12)
#define NX_FILE_AR_WRITE_MASK (0x0F)
#define NX_FILE_AR_WRITE_OFFSET (8)
#define NX_FILE_AR_READWRITE_MASK (0x0F)
#define NX_FILE_AR_READWRITE_OFFSET (4)
#define NX_FILE_AR_CHANGE_MASK (0x0F)
#define NX_FILE_AR_CHANGE_OFFSET (0)
#define NX_FILE_MAX_FILE_NUMBER (0x1F)

#define NX_FILE_NDEF_FILE_NO 2
#define NX_FILE_SETTING_FILEOPTION_SDM_ENABLED (1 << 6)
#define NX_FILE_SETTING_FILEOPTION_DEFERRED_CONF_ENABLED (1 << 3)
#define NX_FILE_SETTING_DEFEROPTION_SDM_ENC_ENABLED (1 << 0)
#define NX_FILE_SDM_OPTIONS_VCUID (1 << 7)
#define NX_FILE_SDM_OPTIONS_SDMReadCtr (1 << 6)
#define NX_FILE_SDM_OPTIONS_SDMReadCtrLimit (1 << 5)
#define NX_FILE_SDM_OPTIONS_SDMENCFileData (1 << 4)
#define NX_FILE_SDM_OPTIONS_GPIOStatus (1 << 3)
#define NX_FILE_SDM_OPTIONS_ENCODING_ASCII (1 << 0)
#define NX_FILE_SDM_OPTIONS_VCUID_DISABLED (0 << 7)
#define NX_FILE_SDM_OPTIONS_SDMReadCtr_DISBALED (0 << 6)
#define NX_FILE_SDM_OPTIONS_SDMReadCtrLimit_DISABLED (0 << 5)
#define NX_FILE_SDM_OPTIONS_SDMENCFileData_DISABLED (0 << 4)
#define NX_FILE_SDM_OPTIONS_GPIOStatus_DISABLED (0 << 3)
#define NX_FILE_SDM_OPTIONS_ENCODING_ASCII_DISABLED (0 << 0)
#define NX_FILE_SDM_OPTIONS_VCUID_BITSHIFT (7)
#define NX_FILE_SDM_OPTIONS_SDMReadCtr_BITSHIFT (6)
#define NX_FILE_SDM_OPTIONS_SDMReadCtrLimit_BITSHIFT (5)
#define NX_FILE_SDM_OPTIONS_SDMENCFileData_BITSHIFT (4)
#define NX_FILE_SDM_OPTIONS_GPIOStatus_BITSHIFT (3)
#define NX_FILE_SDM_OPTIONS_ENCODING_ASCII_BITSHIFT (0)

#define NX_FILE_SDM_OFFSET_MAX 0xFFFFFF
#define NX_FILE_SDM_ENC_LEN_MAX 0xFFFFFF
#define NX_FILE_SDM_READ_CTR_LIMIT_MAX 0xFFFFFF

#define NX_KEY_MGMT_APP_MASTER_KEY_NUMBER 0
#define NX_KEY_MGMT_MIN_APP_KEY_NUMBER 0
#define NX_KEY_MGMT_MAX_APP_KEY_NUMBER 4
#define NX_KEY_MGMT_MIN_CRYPTO_KEY_NUMBER 0x10
#define NX_KEY_MGMT_MAX_CRYPTO_KEY_NUMBER 0x17

#define NX_FILE_SDMMetaRead_OFFSET (12)
#define NX_FILE_SDMMetaRead_MASK (0xF)
#define NX_FILE_SDMFileRead_OFFSET (8)
#define NX_FILE_SDMFileRead_MASK (0xF)
#define NX_FILE_SDMFileRead2_OFFSET (4)
#define NX_FILE_SDMFileRead2_MASK (0xF)
#define NX_FILE_SDMCtrRet_OFFSET (0)
#define NX_FILE_SDMCtrRet_MASK (0xF)

#define NX_MANAGE_GPIO_NFC_AND_OUTPUT_MASK (0x83)
#define NX_PUBLIC_KEY_LENGTH 65
#define NX_SHARED_SECRET_LENGTH 32
#define NX_ECDH_EPHEM_NISTP256_KEY_ID 0xFE
#define NX_ECDH_EPHEM_BRAINPOOL256_KEY_ID 0xFF

#define NX_RAW_SIGNATURE_LENGTH 64

#define NX_MGMT_CRYPTO_SUPPORT_ASYM (1 << 1)
#define NX_MGMT_CRYPTO_SUPPORT_SYM (1 << 0)

/** Number of metadata bytes in CA root key type */
#define NX_CA_ROOT_KEY_META_DATA_BYTES 7

#define NX_KEY_MGMT_APP_MASTER_KEY_ID 0
#define NX_KEY_MGMT_APP_KEY_ID_1 1
#define NX_KEY_MGMT_APP_KEY_ID_2 2
#define NX_KEY_MGMT_APP_KEY_ID_3 3
#define NX_KEY_MGMT_APP_KEY_ID_4 4
#define NX_KEY_MGMT_MIN_APP_KEY_NUMBER 0
#define NX_KEY_MGMT_MAX_APP_KEY_NUMBER 4
#define NX_KEY_MGMT_MIN_CRYPTO_KEY_NUMBER 0x10
#define NX_KEY_MGMT_MAX_CRYPTO_KEY_NUMBER 0x17

#define NX_KEY_MGMT_CRYPTO_AES_KEY_ID_0x10 0x10
#define NX_KEY_MGMT_CRYPTO_AES_KEY_ID_0x11 0x11
#define NX_KEY_MGMT_CRYPTO_AES_KEY_ID_0x12 0x12
#define NX_KEY_MGMT_CRYPTO_AES_KEY_ID_0x13 0x13
#define NX_KEY_MGMT_CRYPTO_AES_KEY_ID_0x14 0x14
#define NX_KEY_MGMT_CRYPTO_AES_KEY_ID_0x15 0x15
#define NX_KEY_MGMT_CRYPTO_AES_KEY_ID_0x16 0x16
#define NX_KEY_MGMT_CRYPTO_AES_KEY_ID_0x17 0x17

#define NX_FILE_AR_READ_BIT_OFFSET 12
#define NX_FILE_AR_WRITE_BIT_OFFSET 8
#define NX_FILE_AR_READWRITE_BIT_OFFSET 4
#define NX_FILE_AR_CHANGE_BIT_OFFSET 0

#define NX_FILE_OPTION_SDM_ENABLED (1 << 6)
#define NX_FILE_OPTION_SDM_DISBALED (0 << 6)
#define NX_FILE_OPTION_SDM_BITSHIFT (6)
#define NX_FILE_OPTION_SDM_MASK (0x40)
#define NX_FILE_OPTION_DEFERRED_ENABLED (1 << 3)
#define NX_FILE_OPTION_DEFERRED_DISABLED (0 << 3)
#define NX_FILE_OPTION_DEFERRED_BITSHIFT (3)
#define NX_FILE_OPTION_COMM_MODE_MASK 0x03

#define NX_FILE_SDM_OPTIONS_VCUID (1 << 7)
#define NX_FILE_SDM_OPTIONS_SDMReadCtr (1 << 6)
#define NX_FILE_SDM_OPTIONS_SDMReadCtrLimit (1 << 5)
#define NX_FILE_SDM_OPTIONS_SDMENCFileData (1 << 4)
#define NX_FILE_SDM_OPTIONS_GPIOStatus (1 << 3)
#define NX_FILE_SDM_OPTIONS_ENCODING_ASCII (1 << 0)

#define NX_DADA_MGMT_MAX_FILE_SIZE 0xFFFFFF
#define NX_DADA_MGMT_FILE_SIZE_ENTIRE_FILE 0x1000000

// Key ID used in ECDH
// 'FE': Use NIST 256 ephemeral keys
// 'FF': Use Brainpool 256 ephemeral keys
#define NX_KEY_ID_EPHEM_NISTP256 0xFE
#define NX_KEY_ID_EPHEM_BP256 0xFF

#define NX_SESSION_KEY_SIZE_BIT_AES128 (1 << 0)
#define NX_SESSION_KEY_SIZE_BIT_AES256 (1 << 1)

#define NX_KEY_TRANSIENT_BUF_SLOT_MASK 0x80
#define NX_KEY_STATIC_BUF_SLOT_MASK 0xC0

#define NX_PROCESSSM_PLAIN_TEXT_LENGTH_MAX 240
#define NX_PROCESSSM_PLAIN_TEXT_LENGTH_MIN 1

#define NX_ACCESS_CONDITION_BIT_MASK 0x0F
#define NX_COMM_MODE_BIT_MASK 0x03
#define NX_COMM_MODE_BIT_SHIFT 4

#define NX_ISO_INTERNAL_AUTH_RND_LENGTH 16
#define NX_ISO_INTERNAL_AUTH_OPTSA_MAX_LENGTH 233

#define NX_AC_BITMAP_INVALID 0xFFFF
#define NX_AC_BITMAP_MAX                                                                           \
    ((1 << Nx_AC_Bitmap_13_Shift) | (1 << Nx_AC_Bitmap_12_Shift) | (1 << Nx_AC_Bitmap_11_Shift) |  \
        (1 << Nx_AC_Bitmap_10_Shift) | (1 << Nx_AC_Bitmap_9_Shift) | (1 << Nx_AC_Bitmap_8_Shift) | \
        (1 << Nx_AC_Bitmap_7_Shift) | (1 << Nx_AC_Bitmap_6_Shift) | (1 << Nx_AC_Bitmap_5_Shift) |  \
        (1 << Nx_AC_Bitmap_4_Shift) | (1 << Nx_AC_Bitmap_3_Shift) | (1 << Nx_AC_Bitmap_2_Shift) |  \
        (1 << Nx_AC_Bitmap_1_Shift) | (1 << Nx_AC_Bitmap_0_Shift))

#define NX_VERSION_MAX_UID_LENGTH 10
#define NX_VERSION_UID_FORMAT_INVALID 0xFF

#endif /* NX_CONST_H */
