/* Copyright 2019-2021 NXP
 * 
 * SPDX-License-Identifier: BSD-3-Clause
 * 
 * 
 */

#ifndef NX_PKG_VERSION_INFO_H_INCLUDED
#define NX_PKG_VERSION_INFO_H_INCLUDED

/* clang-format off */
#define NX_PKG_PROD_NAME          "NX_PKG"
#define NX_PKG_VER_STRING_NUM     "v02.04.00_20241126"
#define NX_PKG_PROD_NAME_VER_FULL "NX_PKG_v02.04.00_20241126"
#define NX_PKG_VER_MAJOR          (2u)
#define NX_PKG_VER_MINOR          (4u)
#define NX_PKG_VER_DEV            (0u)

/* v02.04 = 20004u */
#define NX_PKG_VER_MAJOR_MINOR ( 0 \
    | (NX_PKG_VER_MAJOR * 10000u)    \
    | (NX_PKG_VER_MINOR))

/* v02.04.00 = 200040000ULL */
#define NX_PKG_VER_MAJOR_MINOR_DEV ( 0 \
    | (NX_PKG_VER_MAJOR * 10000*10000u)    \
    | (NX_PKG_VER_MINOR * 10000u)    \
    | (NX_PKG_VER_DEV))

/* clang-format on */

/* Version Information:
 * Generated by:
 *     scripts\version_info.py (v2019.01.17_00)
 * 
 * Do not edit this file. Update:
 *     ./version_info.txt instead.
 * 
 * prod_name = "NX_PKG"
 * 
 * prod_desc = "NX Package"
 * 
 * lang_c_prefix = prod_name.upper()
 * 
 * lang_namespace = ""
 * 
 * v_major  = "02"
 * 
 * v_minor  = "04"
 * 
 * v_dev    = "00"
 * 
 * # Develop Branch
 * v_meta   = ""
 * 
 * maturity = "B"
 * 
 */

#endif /* NX_PKG_VERSION_INFO_H_INCLUDED */
